title: Discover Mastodon Africa
email: wogan@protocol7.co.za
description: >- # this means to ignore newlines until "baseurl:"
  Discover African-based instances of the decentralized Mastodon social network.
baseurl: "" # the subpath of your site, e.g. /blog
domain: discover.mastodon.africa
url: "https://discover.mastodon.africa" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

collections:
  reports:
    output: true